# Generated by Django 3.1.8 on 2021-06-04 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210604_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='one_time_pickup',
            field=models.DateField(default=datetime.date(2021, 6, 4)),
        ),
        migrations.AddField(
            model_name='customer',
            name='pickup_day',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
