# Generated by Django 3.1.8 on 2021-06-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210604_1719'),
        ('customers', '0002_auto_20210604_1901'),
    ]

    operations = [
    ]
