# Generated by Django 3.1.8 on 2021-06-07 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210604_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='one_time_pickup',
            field=models.DateField(default=datetime.date(2021, 6, 7)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='suspension_end',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='suspension_start',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
