# Generated by Django 3.1.8 on 2021-06-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20210607_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='one_time_pickup',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='customer',
            name='suspension_end',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='customer',
            name='suspension_start',
            field=models.DateField(default=None),
        ),
    ]
