# Generated by Django 3.1.8 on 2021-06-08 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20210607_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='one_time_pickup',
            field=models.DateField(default=datetime.date(2021, 6, 8)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='suspension_end',
            field=models.DateField(default=datetime.date(2021, 6, 8)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='suspension_start',
            field=models.DateField(default=datetime.date(2021, 6, 8)),
        ),
    ]
