# Generated by Django 3.1.8 on 2021-06-09 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20210608_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='one_time_pickup',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='suspension_end',
            field=models.DateField(default=datetime.date(2021, 6, 9)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='suspension_start',
            field=models.DateField(default=datetime.date(2021, 6, 9)),
        ),
    ]
