# Generated by Django 3.1.8 on 2021-06-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20210609_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='suspension_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='suspension_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
